'''
Example: python ensemble_PDB.py --dir=/dors/wankowicz_lab/stephanie/serine_protease --protease='elastase' --seq='VVGGTEAQRNSWPSQISLQYRSGSSWAHTCGGTLIRQNWVMTAAHCVDRELTFRVVVGEHNLNQNNGTEQYVGVQKIVVHPYWNTDDVAAGYDIALLRLAQSVTLNSYVQLGVLPRAGTILANNSPCYITGWGLTRTNGQLAQTLQQAYLPTVDYAICSSSSYWGSTVKNSMVCAGGDGVRSGCQGDSGGPLHCLVNGQYAVHGVTSFVSRLGCNVTRKPTVFTRVSAYISWINNVIASN' --ref_pdb='6EST' --ref_chain='A' --protein_name='elastate' --organism='Porcine'
'''
